title: Nima Gharaee
description: this is the test website using just the docs 
theme: just-the-docs

url: https://YOUR-SITE-NAME.github.io

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
